
####### Generated by vagrant provisioning #######
### Core command shortcut ###

# Bash completition for running core nodes
. /etc/bash_completion

# Bash completition of core nodes to ccmd command
complete -W '$(ccmd -p nodes)' ccmd
